version: '2.1'
services:
  postgres:
    image: postgres:13
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=uphold
      - POSTGRES_PASSWORD=postgres
    volumes:
        - ./postgres:/var/lib/postgresql
    ports:
        - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  runserver:
    image: gcr.io/uphold/oscillator-bot
    working_dir: /usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "npm run generate && npm run serve"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CURRENCY_PAIRS=XAU-USD,BTC-USD,XAG-USD,EUR-USD
      - FETCH_INTERVAL=5000
      - PRICE_CHANGE_PERCENTAGE=0.0001
    ports:
      - "3000:3000"
    links:
      - postgres